name: Java CI

on: push

jobs:
  build:
    runs-on: mac-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11.0.10
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.10
      - name: Build with Maven
        run: mvn clean install
